### ISSUE TITLE
Document `h`-stores

### ISSUE THREAD

**Issue by lr4d** [blue-yonder/storefact#12]
At kartothek (https://github.com/JDASoftwareGroup/kartothek) storefact is used in tests, example code and its usage is recommended.

We are currently in the process of documenting the usage of kartothek. Since we require `h` store factories it would be great if there were some upstream documentation on these stores, so that new users can get started smoothly.

This generalizes #4 to all `h`-stores

**Comment by lr4d** [comment]
I just realized `hfs` and `hs3` are actually mentioned in the reference documentation of `get_store`. 

Still, `hmemory` and `hazure` are not mentioned, and no mention is made in `get_store_from_url` either

**Comment by fmarczin** [comment]
Is there any chance that you might provide a PR for this?

**Comment by lr4d** [comment]
Not currently. If we start getting more issues about this in kartothek, I will think about it.

**Comment by Fra-nk** [comment]
I think this is resolved with 41df98c?
