### ISSUE TITLE
urls don't have option to pass default protocol and blob endpoint url

### ISSUE THREAD

**Issue by adityajaroli** [blue-yonder/storefact#22]
Looking for a way to contribute this feature but seems like there is permission issue.

I am looking to support urls like this which can have DefaultEndpointsProtocol and  BlobEndpoint mentioned.
url = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1"

**Comment by adityajaroli** [comment]
Hi @crepererum @fmarczin @theMarix @jank, I am unable to contribute to this repo. Could you please help?

**Comment by crepererum** [comment]
I'm no longer associated w/ the company or project.

**Comment by adityajaroli** [comment]
Received required access!
