### ISSUE TITLE
remove outdated reg package

### ISSUE THREAD

**Issue by bjoernmeier** [blue-yonder/storefact#8]
As the reg package https://pypi.org/project/reg/ has seen its last update in 2016-12-23 it seems it is unsupported. The reg package uses [inspect.getargspec](https://docs.python.org/3.6/library/inspect.html#inspect.getargspec) which is deprecated since Python 3.0 and creates a lot of deprecation messages like this:
```result = inspect.getargspec(func)
venv/lib/python3.6/site-packages/reg/arginfo.py:36: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```

Can you remove or replace it please?

**Comment by criemen** [comment]
Felix release 0.8.4 removing the reg package some days ago.
